### PR TITLE
Add module which use TF2.6

### PR DESCRIPTION
**Pull request by Healthborn**
- 1 module for photon fast simulation
- 1 tool for TF graph loading

### CODE REVIEW

**Comment by knoepfel** [comment]
trigger build

**Comment by mhlswang** [comment]
I looked at the code and it looks good overall. Good that the newer SavedModel format is used here, eliminating the need for pb format models, and simplifying things. Just a minor comment -- in TFLoaderMLP_tool, I see pars being copied to dst_x, y, and z but not sure if they are used anywhere?

**Comment by lgarren** [comment]
@mhlswang a simple search on TFLoaderMLP_tool.cc shows that dst_x, etc. are used.

**Comment by Healthborn** [comment]
Sorry for responding so late.
Yes, dst_x, y, z are used to assign values to tensorflow::Tensor pos_x, y, z.
It is a bit weird (I referenced some existing code).

**Comment by mhlswang** [comment]
Yes, you're right.  Sorry, it was my fault, I misread your code.  I see how how dst_x, y, and z are used to copy the par values into pos_x, y, and z which are inputs to the ML model.  Thanks for clarifying.

**Comment by lgarren** [comment]
approve

**Pull request merged**
