### PR TITLE
Enable graph lookup by path

### PR DESCRIPTION
**Pull request by Healthborn**
code update

### CODE REVIEW

**Comment by Healthborn** [comment]
The change has been previously reviewed without any concern.
This update only applies the change based on the latest larsimdnn code.

**Comment by lgarren** [comment]
trigger build

**Comment by tomjunk** [comment]
Well, I don't see anything in this PR that would break the operation of what it's trying to do, but there are some things that could be misleading if someone wanted to debug or maintain the code.

1)  The cout statements do not identify what piece of code has failed.  Example:

 if (!sp.find_file(ModelName, GraphFileWithPath)) {
      std::cout << "Failed to load SavedModel in : " << sp.to_string() << "\n";
      return;
    }

As far as I can tell, this call to find_file() really finds a directory and does not load anything.  It might be nice to say that, and also print out what was failed to be found (ModelName, which is really a directory name).

2)  What happens if the lookup fails?  The method simply returns.  I assume problems will ensue later on when modelbundle->GetSession()->Run() is called from Predict().  There are probably enough breadcrumbs in the logfile to find this.   One could throw an exception instead when files or directories are not found.

**Comment by knoepfel** [comment]
@Healthborn, can you address @tomjunk's concerns?

**Comment by Healthborn** [comment]
@tomjunk Thanks a lot for the very nice suggestions!
As we need the module urgently and all checked have passed/the branch has no conflicts with the base branch (which is Extremely difficult for me to achieve), I would like to first merge the change, and address the concerns in a separate PR.

**Comment by knoepfel** [comment]
@Healthborn, no LArSoft release is planned for this week.  You should have time to fix the issues Tom brought up.

**Comment by Healthborn** [comment]
@knoepfel, I'm not confident that I can solve the problem in several week.

**Comment by Healthborn** [comment]
Can anyone help to merge this PR?

**Comment by knoepfel** [comment]
@Healthborn, in order to merge this PR, we need L2 and L1 approval.

Tom is an L2 approver who suggested some minor changes—he asked for adding a little more information to the `std::cout` statement, and he brought up whether you should just `return` from a function if the model could not be found.  Probably you should throw an exception instead.

These changes can be made by adding one commit to your local repository and then pushing that commit to your fork.  If you are having trouble with that, we should meet via Zoom so we can get that sorted out.

**Comment by knoepfel** [comment]
Closed in favor of PR #12.

**Pull request closed without merging**
