### PR TITLE
Enable graph lookup by path

### PR DESCRIPTION
**Pull request by tomjunk**
This is a version of Muve's PR #11 with my comments on more information in cout statements and exceptions thrown if models could not be found.

### CODE REVIEW

**Review by knoepfel — COMMENTED** [review]
Looks good to me, @tomjunk.  Thanks

**Comment by knoepfel** [comment]
trigger build

**Comment by lgarren** [comment]
@LArSoft/level-2-managers We need approval immediately if this PR is to go into this weeks' release.

**Comment by lgarren** [comment]
approve

**Pull request merged**
