### PR TITLE
Change the method to find where the graph lives

### PR DESCRIPTION
**Pull request by Healthborn**
Using cet::search_path to search where the graph lives instead of directly passing a directory.

### CODE REVIEW

**Comment by mhlswang** [comment]
switching to cet::search_path to locate input model file makes interface consistent with that in larrecodnn; looks good to me.

**Comment by lgarren** [comment]
code-checks

**Comment by lgarren** [comment]
@Healthborn  This PR conflicts with the head of develop. Please update to match the head of develop.

**Comment by knoepfel** [comment]
@Healthborn, are you able to rebase this PR on top of the latest `develop`?

**Comment by Healthborn** [comment]
sorry, let me do it as soon as possible.

**Comment by Healthborn** [comment]
@knoepfel I don't understand what is the conflict...

**Comment by knoepfel** [comment]
@Healthborn, your repository history is not compatible with mainline development in LArSoft (e.g. it doesn't include a `.clang-format` file).  You need to resolve the history issue by either git-merging LArSoft's `develop` branch with yours, or by trying to do an explicit git rebase of your branch.  I've also attached a [larsimdnn.patch](https://github.com/LArSoft/larsimdnn/files/10539536/larsimdnn.patch) file, which should simplify this for you.  Instructions:

- Download the patch file and put it somewhere outside of your local `larsimdnn` repository.
- Execute `patch -p1 < /path/to/larsimdnn.patch`
- Commit all of the changes and push to this PR.

Once you do that, everything should work okay.  Let me know if it doesn't.

**Comment by Healthborn** [comment]
It's a bit complex. Let me close this PR, clone the package and re-commit.

**Pull request closed without merging**
